export type JTSayItem = {
  additionalValue?: number;
  appMsg?: string;
  autoHotCount?: number;
  category?: number;
  certification?: any;
  commentSetting?: number;
  commentTime?: number;
  content: string;
  countOfAgree?: number;
  countOfCollect?: any;
  countOfComment?: number;
  data?: any;
  delType?: number;
  digest?: any;
  foreignId?: any;
  goodArticleFlag?: any;
  hotArticleFlag?: any;
  hotDay?: any;
  hotTopFlag?: number;
  id?: number;
  indexRecommendFlag?: any;
  mobileCode?: string;
  mockTrading?: any;
  pictures?: string;
  sayFlags?: [];
  sendTime?: number;
  senderId?: number;
  senderNickName?: string;
  senderPhoto: string;
  source?: string;
  squareTopFlag?: number;
  status?: number;
  sumScore?: any;
  tabType?: any;
  tags?: string;
  thumbnail?: any;
  title?: any;
  topFlag?: number;
  userArticleTopFlag?: any;
  userTopFlag?: any;
  videoContent?: any;
  videoTitle?: any;
  videoType?: number;
  voteInfo?: any;
};

export type JTSayListItem = {
  say: JTSayItem;
  author: any;
};
